import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { HerouiProvider } from '@/providers'
import { AuthProvider } from '@/providers/AuthContext'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prello',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen min-h-screen bg-zinc-50 text-zinc-900`}>
        <HerouiProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </HerouiProvider>
      </body>
    </html>
  )
}
