import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar.jsx'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prello',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-cyan-500 to-blue-500`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
