import { Inter } from 'next/font/google'
import { Navbar } from '@/components'
import { HerouiProvider } from '@/providers'
import { AuthProvider } from '@/providers/AuthContext'
import '../styles/globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prello',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} h-screen min-h-screen bg-pastel-page text-pastel-text antialiased bg-fixed`}>
        <HerouiProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </HerouiProvider>
      </body>
    </html>
  )
}
