import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { Providers } from '@/providers/herouiProvider'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prello',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen bg-gradient-to-r from-cyan-500 to-blue-500`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
